"""Non-ergodic dataset generation and ground-truth belief state computation.

Each sequence in the dataset is generated by exactly ONE of K Mess3 sources,
chosen uniformly at random per sequence.  This makes the joint process over
all sequences non-ergodic: there is no single stationary distribution.

Mess3 convention (matches fwh_core transition_matrices.py):
    T[obs, state_from, state_to] = P(emit obs AND transition to state_to | in state_from)
    Row sum:  sum_{obs, state_to} T[obs, s, state_to] = 1  for each s
    Belief update: new_b = b @ T[obs]  (row-vector left-multiply), then normalize
    Emission prob: p(x | b) = sum_s b[s] * T[x, s, :].sum()
"""

from __future__ import annotations

import numpy as np
from typing import Optional

from nonergodic.config import MESS3_PARAMS, K, VOCAB_SIZE, BOS_TOKEN, N_OBS


# ---------------------------------------------------------------------------
# Mess3 transition matrix (pure numpy, mirrors fwh_core exactly)
# ---------------------------------------------------------------------------

def make_mess3_matrix(a: float, x: float) -> np.ndarray:
    """Return the Mess3 transition tensor T of shape (N_OBS, N_STATES, N_STATES).

    Parameters
    ----------
    a : diagonal dominance parameter ∈ (0,1)
    x : cross-emission probability ∈ (0, 0.5)
    """
    b = (1 - a) / 2
    y = 1 - 2 * x

    ay, bx, by, ax = a * y, b * x, b * y, a * x

    T = np.array([
        # obs = 0
        [[ay, bx, bx],
         [ax, by, bx],
         [ax, bx, by]],
        # obs = 1
        [[by, ax, bx],
         [bx, ay, bx],
         [bx, ax, by]],
        # obs = 2
        [[by, bx, ax],
         [bx, by, ax],
         [bx, bx, ay]],
    ], dtype=np.float64)

    # sanity check: rows should be valid distributions
    row_sums = T.sum(axis=(0, 2))   # sum over obs and next_state for each curr_state
    assert np.allclose(row_sums, 1.0), f"Row sums not 1: {row_sums}"
    return T


def stationary_distribution(T: np.ndarray) -> np.ndarray:
    """Compute stationary distribution of T by left-eigenvector of T_net.

    For symmetric Mess3 this is always [1/3, 1/3, 1/3], but we compute it
    properly for generality.
    """
    T_net = T.sum(axis=0)          # shape (N_STATES, N_STATES)
    eigenvalues, left_evecs = np.linalg.eig(T_net.T)
    idx = np.argmin(np.abs(eigenvalues - 1.0))
    stat = left_evecs[:, idx].real
    stat = np.abs(stat)
    return stat / stat.sum()


# Build the K transition matrices once at module import
TRANSITION_MATRICES: list[np.ndarray] = [
    make_mess3_matrix(**params) for params in MESS3_PARAMS
]
STATIONARY_DISTS: list[np.ndarray] = [
    stationary_distribution(T) for T in TRANSITION_MATRICES
]


# ---------------------------------------------------------------------------
# Single-sequence generation
# ---------------------------------------------------------------------------

def sample_sequence(
    source_idx: int,
    seq_len: int,
    rng: np.random.Generator,
) -> tuple[np.ndarray, np.ndarray]:
    """Sample one sequence of Mess3 observations and the corresponding states.

    Returns
    -------
    obs : int array of shape (seq_len,), values in {0, 1, 2}
    states : int array of shape (seq_len,), values in {0, 1, 2}
        states[t] is the hidden state AFTER emitting obs[t]
    """
    T = TRANSITION_MATRICES[source_idx]
    pi = STATIONARY_DISTS[source_idx]

    n_states = T.shape[1]
    obs_seq = np.empty(seq_len, dtype=np.int64)
    state_seq = np.empty(seq_len, dtype=np.int64)

    state = rng.choice(n_states, p=pi)

    for t in range(seq_len):
        # Joint distribution over (obs, next_state) given current state
        probs = T[:, state, :].flatten()        # shape (N_OBS * N_STATES,)
        probs = np.maximum(probs, 0.0)
        probs /= probs.sum()
        idx = rng.choice(len(probs), p=probs)
        obs = idx // n_states
        next_state = idx % n_states
        obs_seq[t] = obs
        state_seq[t] = next_state
        state = next_state

    return obs_seq, state_seq


# ---------------------------------------------------------------------------
# Batch generation
# ---------------------------------------------------------------------------

def generate_batch(
    seq_len: int,
    batch_size: int,
    rng: np.random.Generator,
) -> dict[str, np.ndarray]:
    """Generate a batch of non-ergodic sequences.

    Each sequence is drawn independently from one randomly-selected source.

    Returns
    -------
    dict with keys:
        "tokens"       : int array (batch_size, seq_len+1), includes leading BOS
        "source_ids"   : int array (batch_size,), which source was used
        "obs"          : int array (batch_size, seq_len), raw observations
        "states"       : int array (batch_size, seq_len), hidden states after each obs
    """
    source_ids = rng.integers(0, K, size=batch_size)

    all_obs = np.empty((batch_size, seq_len), dtype=np.int64)
    all_states = np.empty((batch_size, seq_len), dtype=np.int64)

    for i in range(batch_size):
        obs, states = sample_sequence(source_ids[i], seq_len, rng)
        all_obs[i] = obs
        all_states[i] = states

    # Prepend BOS token
    bos_col = np.full((batch_size, 1), BOS_TOKEN, dtype=np.int64)
    tokens = np.concatenate([bos_col, all_obs], axis=1)   # (B, seq_len+1)

    return {
        "tokens": tokens,
        "source_ids": source_ids,
        "obs": all_obs,
        "states": all_states,
    }


# ---------------------------------------------------------------------------
# Ground-truth belief state computation
# ---------------------------------------------------------------------------

def compute_belief_states(
    obs_sequence: np.ndarray,
    true_source: Optional[int] = None,
) -> dict[str, np.ndarray]:
    """Compute ground-truth belief states for a single observation sequence.

    The optimal predictor's internal state at position t is:

        b_t = { w_k(t), h_k(t) }_{k=0}^{K-1}

    where:
        w_k(t)  = P(source=k | obs_{1:t})   (source weight)
        h_k(t)  = P(hidden state | obs_{1:t}, source=k)   (per-source hidden belief)

    The full predictive vector is the (3K)-dim concatenation of w_k(t)*h_k(t),
    which lives in the (3K-1)-simplex Δ^{3K-1} = Δ^8.

    Parameters
    ----------
    obs_sequence : int array of shape (T,)
    true_source  : if provided, record it for analysis

    Returns
    -------
    dict with keys:
        "source_weights"    : (T+1, K)        w_k(t) for t=0..T
        "hidden_beliefs"    : (T+1, K, 3)     h_k(t) for t=0..T
        "joint_beliefs"     : (T+1, 3*K)      w_k(t)*h_k(t) concatenated, t=0..T
        "log_seq_probs"     : (T+1, K)        log p_k(obs_{1:t}) for t=0..T
        "source_entropies"  : (T+1,)          H[source | obs_{1:t}]
        "hidden_entropies"  : (T+1, K)        H[hidden | obs_{1:t}, source=k]
    """
    T = len(obs_sequence)

    # --- initialise at t=0 (after BOS, before any observations) ---
    # Equal source prior; per-source belief = stationary
    source_weights = np.zeros((T + 1, K))
    source_weights[0] = np.ones(K) / K

    hidden_beliefs = np.zeros((T + 1, K, N_OBS))
    for k in range(K):
        hidden_beliefs[0, k] = STATIONARY_DISTS[k]

    log_seq_probs = np.zeros((T + 1, K))   # log p_k(obs_{1:t}), zero at t=0

    for t, obs in enumerate(obs_sequence):
        t_post = t + 1   # index into the output arrays

        new_hidden = np.zeros((K, N_OBS))
        new_log_probs = np.zeros(K)

        for k in range(K):
            T_k = TRANSITION_MATRICES[k]
            # Unnormalized belief update: b' = b @ T_k[obs]
            unnorm = hidden_beliefs[t, k] @ T_k[obs]    # shape (3,)
            p_obs_given_k = unnorm.sum()                 # p_k(obs_t | obs_{1:t-1})
            new_log_probs[k] = log_seq_probs[t, k] + np.log(p_obs_given_k + 1e-300)
            new_hidden[k] = unnorm / (p_obs_given_k + 1e-300)

        # Numerically stable source weight update
        log_source = log_seq_probs[t] + np.log(1.0 / K)  # log posterior
        log_source_post = new_log_probs + np.log(1.0 / K)
        log_source_post -= log_source_post.max()
        source_post = np.exp(log_source_post)
        source_post /= source_post.sum()

        source_weights[t_post] = source_post
        hidden_beliefs[t_post] = new_hidden
        log_seq_probs[t_post] = new_log_probs

    # Joint belief vector: w_k * h_k(s) concatenated over k
    # Shape: (T+1, 3*K)
    joint_beliefs = (source_weights[:, :, None] * hidden_beliefs).reshape(T + 1, K * N_OBS)

    # Entropies
    eps = 1e-300
    source_entropies = -np.sum(source_weights * np.log(source_weights + eps), axis=1)

    h = hidden_beliefs
    hidden_entropies = -np.sum(h * np.log(h + eps), axis=2)   # (T+1, K)

    return {
        "source_weights": source_weights,           # (T+1, K)
        "hidden_beliefs": hidden_beliefs,           # (T+1, K, 3)
        "joint_beliefs": joint_beliefs,             # (T+1, 3K)
        "log_seq_probs": log_seq_probs,             # (T+1, K)
        "source_entropies": source_entropies,       # (T+1,)
        "hidden_entropies": hidden_entropies,       # (T+1, K)
    }


def compute_belief_states_batch(
    obs_batch: np.ndarray,
    source_ids: Optional[np.ndarray] = None,
) -> dict[str, np.ndarray]:
    """Compute belief states for a batch of observation sequences.

    Parameters
    ----------
    obs_batch  : int array (B, T)
    source_ids : int array (B,), optional

    Returns
    -------
    dict with same keys as compute_belief_states but with a leading batch axis.
    """
    B, T = obs_batch.shape
    results = [compute_belief_states(obs_batch[i]) for i in range(B)]

    return {
        key: np.stack([r[key] for r in results], axis=0)
        for key in results[0]
    }


# ---------------------------------------------------------------------------
# Emission probability (useful for next-token prediction)
# ---------------------------------------------------------------------------

def emission_probs_from_beliefs(
    source_weights: np.ndarray,    # (K,)
    hidden_beliefs: np.ndarray,    # (K, 3)
) -> np.ndarray:
    """Compute P(next_obs=x) from the current joint belief.

    P(x) = sum_k w_k * sum_s h_k(s) * sum_s' T_k[x, s, s']
    """
    probs = np.zeros(N_OBS)
    for k in range(K):
        T_k = TRANSITION_MATRICES[k]
        # P(x | source=k, hidden=s) = T_k[x, s, :].sum()
        emission_k = T_k.sum(axis=2)    # (N_OBS, N_STATES): p(obs | state)
        probs += source_weights[k] * (emission_k @ hidden_beliefs[k])
    return probs
